const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetMirrored
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{Твёрдый: 0},
	{ТайловыйФон2: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт: 0},
	{СквознаяПлатформа: 0},
	{Спрайт2: 0},
	{Синусоида: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Якорь: 0},
	{Текст: 0},
	{Спрайт5: 0},
	{ТайловыйФон3: 0},
	{ТайловыйФон4: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Частицы: 0},
	{Спрайт9: 0},
	{Мышь: 0},
	{Пуля: 0},
	{Спрайт10: 0},
	{Клавиатура: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{баланс: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {}
}